//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoiceProcessingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class audioNote
    {
        public audioNote()
        {
            this.audioTranslations = new HashSet<audioTranslation>();
        }
    
        public int id { get; set; }
        public string audioFileName { get; set; }
        public string description { get; set; }
        public Nullable<int> idLanguage { get; set; }
    
        public virtual language language { get; set; }
        public virtual ICollection<audioTranslation> audioTranslations { get; set; }
    }
}
