//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoiceProcessingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public language()
        {
            this.audioNotes = new HashSet<audioNote>();
        }
    
        public int id { get; set; }
        public string languageName { get; set; }
    
        public virtual ICollection<audioNote> audioNotes { get; set; }
    }
}
